In [20]:
import numpy as np
from math import *
from sklearn.model_selection import train_test_split
from sklearn import datasets
from collections import Counter

iris = datasets.load_iris() 
x = iris.data
y = iris.target
test_list=[5.1,3.0,4.2,1.5]
k=3
print(x)
print(y)
print(len(x))
print(len(y))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [21]:

dt={}
kk=0
for i in range(0,len(x)):
    s=0;
    for j in range(0,len(x[i])):
        s=s+(((x[i][j])-test_list[j])**2)
    rt=sqrt(s);
    dt[rt]=y[kk]
    kk=kk+1
print (dt)


{3.1272991542223783: 0, 3.093541659651604: 0, 3.2093613071762426: 0, 3.0397368307141326: 0, 3.146426544510455: 0, 2.891366458960192: 0, 3.1128764832546763: 0, 3.024896692450835: 0, 3.167017524422623: 0, 3.0495901363953815: 0, 3.0919249667480617: 0, 2.9495762407505253: 0, 3.144837038703278: 0, 3.4942810419312296: 0, 3.4899856733230297: 0, 3.289376840679706: 0, 3.2434549480453714: 0, 3.0870698080866266: 0, 2.947880594596735: 0, 3.0610455730027937: 0, 2.8618176042508368: 0, 2.99833287011299: 0, 3.5411862419251547: 0, 2.7092434368288134: 0, 2.6888659319497505: 0, 2.9086079144497976: 0, 2.8530685235374214: 0, 3.1144823004794877: 0, 2.9410882339705484: 0, 2.924038303442689: 0, 2.9580398915498085: 0, 3.235737937472687: 0, 3.336165463522456: 0, 3.004995840263344: 0, 3.277193921634788: 0, 3.241913015489466: 0, 3.1937438845342627: 0, 3.254228019054596: 0, 3.023243291566195: 0, 3.1796226191169294: 0, 3.2710854467592254: 0, 3.2603680773802215: 0, 2.7982137159266447: 0, 2.6720778431774774: 0, 3.014

In [24]:
dt2={}
for i in sorted(dt):
    dt2[i]=dt[i]
print(dt2)
l1=l2=l3=ma=0
for i in dt2.values():
    if(i==0):
        l1+=1
    if(i==1):
        l2+=1
    if(i==2):
        l3+=1
    k=k-1;
    if(k==0):
        break
print ("output :",0,"->",l1," ",1,"->",l2," ",2,"->",l3)
print("ans_y: ",end="")
ma=max(l1,max(l2,l3))
if(l1==ma):
    print(0)
elif (l2==ma):
    print(1)
else:
    print(2)

{0.4242640687119289: 1, 0.44721359549995815: 1, 0.5477225575051662: 1, 0.58309518948453: 1, 0.6164414002968975: 1, 0.6403124237432853: 1, 0.6480740698407857: 2, 0.6708203932499371: 1, 0.6708203932499374: 1, 0.6708203932499376: 1, 0.7000000000000002: 1, 0.7280109889280523: 1, 0.8000000000000007: 1, 0.8124038404635961: 1, 0.8544003745317535: 1, 0.8660254037844387: 1, 0.871779788708135: 1, 0.8831760866327848: 1, 0.9165151389911682: 1, 0.9165151389911683: 1, 0.9539392014169459: 1, 1.009950493836208: 1, 1.0148891565092222: 2, 1.0344080432788603: 1, 1.0583005244258363: 1, 1.0630145812734653: 1, 1.0816653826391966: 1, 1.1224972160321824: 2, 1.1224972160321829: 1, 1.1269427669584644: 1, 1.126942766958465: 1, 1.174734012447073: 1, 1.2083045973594573: 1, 1.2247448713915892: 2, 1.2409673645990857: 2, 1.244989959798873: 2, 1.24899959967968: 1, 1.2569805089976536: 2, 1.30384048104053: 2, 1.3114877048604: 1, 1.319090595827292: 1, 1.3228756555322954: 1, 1.322875655532296: 1, 1.3379088160259653: 1, 1.