In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x=np.array([[14,5],[16,5],[6,0],[10,1],[8,2],[15,6],[15,7],[8,2],[8,1],[15,4]])


x_avg=x.mean(axis=0)
new_x=x-x_avg
print(new_x)

[[ 2.5  1.7]
 [ 4.5  1.7]
 [-5.5 -3.3]
 [-1.5 -2.3]
 [-3.5 -1.3]
 [ 3.5  2.7]
 [ 3.5  3.7]
 [-3.5 -1.3]
 [-3.5 -2.3]
 [ 3.5  0.7]]


In [3]:
covM=np.dot(new_x.T,new_x)
covM=covM/(len(new_x)-1)
print(covM)

[[14.72222222  8.38888889]
 [ 8.38888889  5.78888889]]


In [4]:
ev,EV=np.linalg.eigh(covM)
print(ev)
print(EV)

[ 0.75163174 19.75947937]
[[ 0.51479058 -0.85731596]
 [-0.85731596 -0.51479058]]


In [5]:
rev_ev=ev[::-1]
rev_EV=EV[::-1]
print(rev_ev)
print(rev_EV)

[19.75947937  0.75163174]
[[-0.85731596 -0.51479058]
 [ 0.51479058 -0.85731596]]


In [6]:
first=(rev_ev[0]/(rev_ev[0]+rev_ev[1]))*100
second=(rev_ev[1]/(rev_ev[0]+rev_ev[1]))*100

print(first,second)

96.335489894056 3.6645101059440126


In [7]:
pc=[]
for i in new_x:
    pc1=np.dot(rev_EV[0], i)
    pc2=np.dot(rev_EV[1], i)
    pc.append([pc1,pc2])
pc=np.array(pc)
print(pc)

[[-3.01843389e+00 -1.70460691e-01]
 [-4.73306582e+00  8.59120466e-01]
 [ 6.41404671e+00 -2.20550373e-03]
 [ 2.46999227e+00  1.19964085e+00]
 [ 3.66983362e+00 -6.87256273e-01]
 [-4.39054043e+00 -5.12986075e-01]
 [-4.90533101e+00 -1.37030204e+00]
 [ 3.66983362e+00 -6.87256273e-01]
 [ 4.18462420e+00  1.70059690e-01]
 [-3.36095928e+00  1.20164585e+00]]


In [8]:
real_ar=[]
for i in range(0,len(pc)):
    a=pc[i][0]*rev_EV[0]
    #b=pc[i][1]*rev_EV[1]
    
    recon=x_avg+a
    #recon=recon+b
    real_ar.append(recon)
    
print(real_ar)

[array([14.08775156,  4.85386133]), array([15.55773288,  5.73653769]), array([ 6.00113537e+00, -1.89081355e-03]), array([9.38243619, 2.02847125]), array([8.35379305, 1.41080423]), array([15.2640804 ,  5.56020885]), array([15.70541858,  5.82521819]), array([8.35379305, 1.41080423]), array([7.91245487, 1.14579489]), array([14.38140404,  5.03019017])]
